---
detectors:
  UncommunicativeVariableName:
    accept:
      - e
      - t
      - _
  TooManyStatements:
    enabled: true
    max_statements: 25
  TooManyMethods:
    enabled: true
    max_methods: 25
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyConstants:
    enabled: true
    max_constants: 30
  LongParameterList:
    enabled: true
    max_params: 10
  TooManyInstanceVariables:
    enabled: true
    max_instance_variables: 10
  DataClump:
    enabled: false
  DuplicateMethodCall:
    enabled: true
    exclude:
      - RailsCron::Railtie#self.register_signal_handlers
      - RailsCron::Lock::SQLiteAdapter#acquire
  MissingSafeMethod:
    enabled: true
    exclude:
      - RailsCron::Coordinator
  ManualDispatch:
    enabled: true
    exclude:
      - RailsCron::Registry#callable?
      - RailsCron::Railtie#self.chain_previous_handler
      - RailsCron::Lock::RedisAdapter#initialize
      - RailsCron::Lock::DispatchLogging#log_dispatch_attempt
      - RailsCron::Registry#validate_entry
      - RailsCron::Coordinator#already_dispatched?
      - RailsCron::Coordinator#cleanup_old_dispatch_records
  UtilityFunction:
    enabled: true
    exclude:
      - RailsCron::Dispatch::DatabaseEngine#cleanup
      - RailsCron::Dispatch::DatabaseEngine#find_by_key
      - RailsCron::Dispatch::DatabaseEngine#find_by_node
      - RailsCron::Dispatch::DatabaseEngine#find_by_status
      - RailsCron::Dispatch::DatabaseEngine#find_dispatch
      - RailsCron::Dispatch::DatabaseEngine#log_dispatch
      - RailsCron::Dispatch::MemoryEngine#build_key
      - RailsCron::Dispatch::RedisEngine#convert_timestamps
      - RailsCron::Lock::DispatchLogging#parse_lock_key
      - RailsCron::Lock::MySQLAdapter#cast_to_boolean
      - RailsCron::Lock::MySQLAdapter#normalize_lock_name
      - RailsCron::Lock::PostgresAdapter#calculate_lock_id
      - RailsCron::Lock::PostgresAdapter#cast_to_boolean
      - RailsCron::Lock::RedisAdapter#generate_lock_value
  FeatureEnvy:
    enabled: true
    exclude:
      - RailsCron::Configuration#handle_known_key
      - RailsCron::Configuration#handle_known_key
      - RailsCron::Configuration#normalize_value
      - RailsCron::Coordinator#find_occurrences
      - RailsCron::Coordinator#already_dispatched?
      - RailsCron::Coordinator#cleanup_old_dispatch_records
  NilCheck:
    enabled: true
    exclude:
      - RailsCron::Coordinator#stop!
      - RailsCron::Lock::RedisAdapter#initialize
      - RailsCron::Lock::MySQLAdapter#cast_to_boolean
      - RailsCron::Coordinator#already_dispatched?
      - RailsCron::Coordinator#cleanup_old_dispatch_records

exclude_paths:
  - spec/**/*
  - db/**/*
  - bin/*
  - config/**/*
  - vendor/**/*
