---
detectors:
  UncommunicativeVariableName:
    accept:
      - e
      - t
      - _
  TooManyStatements:
    enabled: true
    max_statements: 20
  TooManyMethods:
    enabled: true
    max_methods: 20
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyConstants:
    enabled: true
    max_constants: 30
  LongParameterList:
    enabled: true
    max_params: 10
  TooManyInstanceVariables:
    enabled: true
    max_instance_variables: 10
  DataClump:
    enabled: false
  DuplicateMethodCall:
    enabled: true
    exclude:
      - RailsCron::Railtie#self.register_signal_handlers
      - RailsCron::Lock::SQLiteAdapter#acquire
  MissingSafeMethod:
    enabled: true
    exclude:
      - RailsCron::Coordinator
  ManualDispatch:
    enabled: true
    exclude:
      - RailsCron::Registry#callable?
      - RailsCron::Railtie#self.chain_previous_handler
      - RailsCron::Lock::RedisAdapter#initialize
  UtilityFunction:
    enabled: true
    exclude:
      - RailsCron::Registry#callable?
      - RailsCron::Lock::PostgresAdapter#calculate_lock_id
      - RailsCron::Lock::PostgresAdapter#parse_lock_key
      - RailsCron::Lock::PostgresAdapter#cast_to_boolean
      - RailsCron::Lock::RedisAdapter#generate_lock_value
      - RailsCron::Lock::MySQLAdapter#cast_to_boolean
      - RailsCron::Lock::MySQLAdapter#parse_lock_key
      - RailsCron::Lock::MySQLAdapter#truncate_lock_name
      - RailsCron::Lock::MySQLAdapter#normalize_lock_name
  FeatureEnvy:
    enabled: true
    exclude:
      - RailsCron::Configuration#handle_known_key
      - RailsCron::Configuration#normalize_value
      - RailsCron::Coordinator#find_occurrences
      - RailsCron::Lock::SQLiteAdapter#acquire
  NilCheck:
    enabled: true
    exclude:
      - RailsCron::Coordinator#stop!
      - RailsCron::Lock::RedisAdapter#initialize
      - RailsCron::Lock::MySQLAdapter#cast_to_boolean

exclude_paths:
  - spec/**/*
  - db/**/*
  - bin/*
  - config/**/*
  - vendor/**/*
