# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rails_cron.gemspec.
gemspec

group :development, :test do
  gem 'danger'
  gem 'faraday-retry'
  gem 'i18n-tasks', '~> 1.0'
  gem 'pg', '~> 1.1'
  gem 'redis', '~> 5.0'
  gem 'reek'
  gem 'rspec-rails'
  gem 'rubocop-factory_bot'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-rspec_rails'
  gem 'shoulda-matchers'
  gem 'sqlite3'
end

group :test do
  gem 'fakeredis'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end

group :development do
  gem 'ruby-lsp', require: false
  gem 'ruby-lsp-rails', require: false
  gem 'ruby-lsp-rspec', require: false
end
